name: Enrich with Retail Categories
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: clickstream-raw
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: clickstream-cats
    required: true
  - name: redishost
    inputType: FreeText
    description: ''
    defaultValue: redis-11226.c304.europe-west1-2.gce.cloud.redislabs.com
    required: true
  - name: redisuser
    inputType: FreeText
    description: ''
    defaultValue: quixtut
    required: true
  - name: redispw
    inputType: InputTopic
    description: ''
    defaultValue: ''
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
