name: Enrich with Demographic Details
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: clickstream-raw-simple
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: clickstream-userenriched
    required: true
  - name: redishost
    inputType: FreeText
    description: ''
    defaultValue: redis-13908.c304.europe-west1-2.gce.cloud.redislabs.com
    required: true
  - name: redisuser
    inputType: FreeText
    description: ''
    defaultValue: clickstreamboy
    required: true
  - name: redispw
    inputType: FreeText
    description: ''
    defaultValue: M3rl1n-06
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
